# Generated by Django 5.0.7 on 2024-07-16 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 20, 16, 20, 210053), null=True),
        ),
    ]
