# Generated by Django 5.0.7 on 2024-07-16 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_comment_alter_blog_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 21, 7, 41, 885680), null=True),
        ),
    ]
